# Word2vec

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/drive/MyDrive/DataScience/Auditoriski/data/bitcointweets.csv')

In [3]:
df

Fri Mar 23 00:40:32 +0000 2018  \
0      Fri Mar 23 00:40:34 +0000 2018   
1      Fri Mar 23 00:40:35 +0000 2018   
2      Fri Mar 23 00:40:36 +0000 2018   
3      Fri Mar 23 00:40:36 +0000 2018   
4      Fri Mar 23 00:40:36 +0000 2018   
...                               ...   
50853  Fri Mar 23 08:55:16 +0000 2018   
50854  Fri Mar 23 08:55:17 +0000 2018   
50855  Fri Mar 23 08:55:18 +0000 2018   
50856  Fri Mar 23 08:55:19 +0000 2018   
50857  Fri Mar 23 08:55:19 +0000 2018   

      RT @ALXTOKEN: Paul Krugman, Nobel Luddite. I had to tweak the nose of this Bitcoin enemy. He says such foolish things. Here's the link: htt…  \
0      @lopp @_Kevin_Pham @psycho_sage @naval But @Pr...                                                                                             
1      RT @tippereconomy: Another use case for #block...                                                                                             
2                     free coins https://t.co/DiuoePJdap                                                                                             
3      RT @payvxofficial: WE are happy to announce th...                                                                                             
4      Copy successful traders automatically with Bit...                                                                                             
...                                                  ...                                                                                             
50853  RT @fixy_app: Fixy Network brings popular cryp...                                                                                             
50854  RT @bethereumteam: After a successful launch o...                                                                                             
50855  RT @GymRewards: Buy #GYMRewards Tokens, Bonus ...                                                                                             
50856  I added a video to a @YouTube playlist https:/...                                                                                             
50857  RT @Raybambs: Airdrop PhotoCoin Airdrop Round#...                                                                                             

        myresumerocket  16522  0  \
0             BitMocro   1295  0   
1         hojachotopur   6090  0   
2        denies_distro   2626  0   
3           aditzgraha    184  0   
4      VictorS61164810     14  0   
...                ...    ... ..   
50853    quoting_lives   5673  0   
50854       VariPewitt    372  0   
50855     urbancoinerz    557  0   
50856   MRDanishShahab      3  0   
50857        Azriel020   1271  0   

                                                      []  \
0                                           [u'Bitcoin']   
1           [u'blockchain', u'Tipper', u'TipperEconomy']   
2                                                     []   
3                                                     []   
4                                                     []   
...                                                  ...   
50853                                                 []   
50854                                                 []   
50855  [u'GYMRewards', u'ICO', u'cryptocurrency', u'm...   
50856                                                 []   
50857                                     [u'PhotoCoin']   

      <a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>  \
0      <a href="http://twitter.com/download/android" ...                   
1      <a href="http://twitter.com" rel="nofollow">Tw...                   
2      <a href="http://twitter.com" rel="nofollow">Tw...                   
3      <a href="http://twitter.com/download/android" ...                   
4      <a href="http://twitter.com" rel="nofollow">Tw...                   
...                                                  ...                   
50853  <a href="http://twit

In [4]:
df.columns=['date','text','author','id','unknown','tags','url','sentiment']

In [5]:
df

date  \
0      Fri Mar 23 00:40:34 +0000 2018   
1      Fri Mar 23 00:40:35 +0000 2018   
2      Fri Mar 23 00:40:36 +0000 2018   
3      Fri Mar 23 00:40:36 +0000 2018   
4      Fri Mar 23 00:40:36 +0000 2018   
...                               ...   
50853  Fri Mar 23 08:55:16 +0000 2018   
50854  Fri Mar 23 08:55:17 +0000 2018   
50855  Fri Mar 23 08:55:18 +0000 2018   
50856  Fri Mar 23 08:55:19 +0000 2018   
50857  Fri Mar 23 08:55:19 +0000 2018   

                                                    text           author  \
0      @lopp @_Kevin_Pham @psycho_sage @naval But @Pr...         BitMocro   
1      RT @tippereconomy: Another use case for #block...     hojachotopur   
2                     free coins https://t.co/DiuoePJdap    denies_distro   
3      RT @payvxofficial: WE are happy to announce th...       aditzgraha   
4      Copy successful traders automatically with Bit...  VictorS61164810   
...                                                  ...              ...   
50853  RT @fixy_app: Fixy Network brings popular cryp...    quoting_lives   
50854  RT @bethereumteam: After a successful launch o...       VariPewitt   
50855  RT @GymRewards: Buy #GYMRewards Tokens, Bonus ...     urbancoinerz   
50856  I added a video to a @YouTube playlist https:/...   MRDanishShahab   
50857  RT @Raybambs: Airdrop PhotoCoin Airdrop Round#...        Azriel020   

         id  unknown                                               tags  \
0      1295        0                                       [u'Bitcoin']   
1      6090        0       [u'blockchain', u'Tipper', u'TipperEconomy']   
2      2626        0                                                 []   
3       184        0                                                 []   
4        14        0                                                 []   
...     ...      ...                                                ...   
50853  5673        0                                                 []   
50854   372        0                                                 []   
50855   557        0  [u'GYMRewards', u'ICO', u'cryptocurrency', u'm...   
50856     3        0                                                 []   
50857  1271        0                                     [u'PhotoCoin']   

                                                     url     sentiment  
0      <a href="http://twitter.com/download/android" ...   ['neutral']  
1      <a href="http://twitter.com" rel="nofollow">Tw...  ['positive']  
2      <a href="http://twitter.com" rel="nofollow">Tw...  ['positive']  
3      <a href="http://twitter.com/download/android" ...  ['positive']  
4      <a href="http://twitter.com" rel="nofollow">Tw...  ['positive']  
...                                                  ...           ...  
50853  <a href="http://twitter.com" rel="nofollow">Tw...  ['positive']  
50854  <a href="http://twitter.com" rel="nofollow">Tw...  ['positive']  
50855  <a href="http://twitter.com" rel="nofollow">Tw...   ['neutral']  
50856  <a href="http://www.google.com/" rel="nofollow...  ['positive']  
50857  <a href="http://twitter.com/download/android" ...  ['positive']  

[50858 rows x 8 columns]

In [6]:
texts = df['text']

In [8]:
texts

0        @lopp @_Kevin_Pham @psycho_sage @naval But @Pr...
1        RT @tippereconomy: Another use case for #block...
2                       free coins https://t.co/DiuoePJdap
3        RT @payvxofficial: WE are happy to announce th...
4        Copy successful traders automatically with Bit...
                               ...                        
50853    RT @fixy_app: Fixy Network brings popular cryp...
50854    RT @bethereumteam: After a successful launch o...
50855    RT @GymRewards: Buy #GYMRewards Tokens, Bonus ...
50856    I added a video to a @YouTube playlist https:/...
50857    RT @Raybambs: Airdrop PhotoCoin Airdrop Round#...
Name: text, Length: 50858, dtype: object

In [10]:
print(texts[5])

RT @bethereumteam: We're revealing our surprise tomorrow! 
Are you ready to celebrate with us? 😮
#surprise #presents #crypto #bitcoin #ethe…


In [11]:
print(texts[5].split(" "))

['RT', '@bethereumteam:', "We're", 'revealing', 'our', 'surprise', 'tomorrow!', '\nAre', 'you', 'ready', 'to', 'celebrate', 'with', 'us?', '😮\n#surprise', '#presents', '#crypto', '#bitcoin', '#ethe…']


# TOKENIZER (" ")

In [9]:
matrix = []

In [12]:
for text in texts:
  words = text.split(" ")
  matrix.append(words)

In [13]:
matrix

[['@lopp',
  '@_Kevin_Pham',
  '@psycho_sage',
  '@naval',
  'But',
  '@ProfFaustus',
  '(dum',
  'b',
  'a',
  'ss)',
  'said',
  'you',
  'know',
  'nothing',
  'about',
  '#Bitcoin',
  '...',
  '😂😂😂',
  'https://t.co/SBAMFQ2Yiy'],
 ['RT',
  '@tippereconomy:',
  'Another',
  'use',
  'case',
  'for',
  '#blockchain',
  'and',
  '#Tipper.',
  'The',
  '#TipperEconomy',
  '',
  'can',
  'unseat',
  'Facebook',
  'and',
  'change',
  'everything!',
  'ICO',
  'Live',
  'No…'],
 ['free', 'coins', 'https://t.co/DiuoePJdap'],
 ['RT',
  '@payvxofficial:',
  'WE',
  'are',
  'happy',
  'to',
  'announce',
  'that',
  'PayVX',
  'Presale',
  'Phase',
  '1',
  'is',
  'now',
  'LIVE!\n\nSign',
  'up',
  '--&gt;&gt;',
  'https://t.co/dhprzsSxek\nCurrencies',
  'accept…'],
 ['Copy',
  'successful',
  'traders',
  'automatically',
  'with',
  'Bitcoin!',
  '💰💰\n\nI',
  'copy',
  '"Dividend667".',
  'Do',
  'you?\n\n➡️',
  'https://t.co/qb2NXPknVt…',
  'https://t.co/Q43fKQRYzx'],
 ['RT',
  '@bethe

In [15]:
sentences = [text.split("\n") for text in texts]

In [16]:
sentences

[['@lopp @_Kevin_Pham @psycho_sage @naval But @ProfFaustus (dum b a ss) said you know nothing about #Bitcoin ... 😂😂😂 https://t.co/SBAMFQ2Yiy'],
 ['RT @tippereconomy: Another use case for #blockchain and #Tipper. The #TipperEconomy  can unseat Facebook and change everything! ICO Live No…'],
 ['free coins https://t.co/DiuoePJdap'],
 ['RT @payvxofficial: WE are happy to announce that PayVX Presale Phase 1 is now LIVE!',
  '',
  'Sign up --&gt;&gt; https://t.co/dhprzsSxek',
  'Currencies accept…'],
 ['Copy successful traders automatically with Bitcoin! 💰💰',
  '',
  'I copy "Dividend667". Do you?',
  '',
  '➡️ https://t.co/qb2NXPknVt… https://t.co/Q43fKQRYzx'],
 ["RT @bethereumteam: We're revealing our surprise tomorrow! ",
  'Are you ready to celebrate with us? 😮',
  '#surprise #presents #crypto #bitcoin #ethe…'],
 ['One click to start mining cryptocurrencies together with &gt;45K people. #bitcoin  https://t.co/rjZC2dia2S #PaaS #cloudnetwork'],
 ['first speaker @digitsu',
  '',
  '"how we 

# MODEL: embedding model

zbor --> vektor

In [14]:
from gensim.models import Word2Vec

In [20]:
model = Word2Vec(sentences,vector_size=150,min_count=1,window=5,workers=4)

In [40]:
vector = model.wv["#ethereum"]

In [41]:
vector

array([ 0.00762654, -0.00834788,  0.00784092,  0.01706971, -0.02446394,
        0.00305065,  0.01432753,  0.01814196, -0.00548183,  0.0017454 ,
        0.02428181,  0.0034425 , -0.01195326,  0.0146453 , -0.02265634,
       -0.01101642,  0.0013154 , -0.00746681, -0.00979565, -0.00360666,
       -0.00339045,  0.00413031,  0.00504548,  0.00196805,  0.00164256,
        0.00133291, -0.01398712,  0.00202219, -0.01574336, -0.00360798,
       -0.02185955, -0.00400462,  0.01625924, -0.02272477, -0.00983052,
        0.007293  ,  0.00407814, -0.00506135,  0.00740085, -0.01167292,
       -0.02549782,  0.02011572, -0.02218782, -0.01292475,  0.00036937,
       -0.003089  , -0.00901885,  0.01303665,  0.003785  ,  0.0287252 ,
        0.00406868,  0.0001316 , -0.02326688,  0.01514864,  0.00465803,
       -0.00082179,  0.00086286, -0.01160441, -0.0080502 ,  0.01554912,
       -0.00244438,  0.01317993, -0.01384211, -0.00441869,  0.00824406,
       -0.00976614, -0.00634009, -0.00369905, -0.01913634, -0.00

In [30]:
model2 = Word2Vec(matrix,vector_size=150,min_count=1,window=5,workers=4)

In [42]:
vector2 = model2.wv["ethereum"]

In [43]:
vector2

array([ 0.10034432, -0.18648975, -0.15764318,  0.49519828,  0.49294442,
        0.04748066, -0.0136724 ,  0.42665353,  0.0803377 ,  0.00779003,
       -0.13574176, -0.5221692 , -0.06184962,  0.5123592 , -0.00822498,
       -0.06211146,  0.65330964, -0.2377208 ,  0.28102526,  0.51654786,
       -0.24104823, -0.12359151,  0.32836375,  0.35858136,  0.17505522,
        0.00690911,  0.06255936,  0.11518569,  0.01508187, -0.6762063 ,
        0.05964344,  0.17116036,  0.07014356,  0.15051422, -0.27318138,
       -0.44221523,  0.20442978, -0.07818524, -0.44348213, -0.54559594,
       -0.06337097, -0.03853285, -0.27361408, -0.37295914,  0.13856363,
       -0.60988176,  0.5086878 , -0.20089267,  0.16954933,  0.4064412 ,
        0.2610055 ,  0.1589837 , -0.31915927, -0.29463252,  0.2889203 ,
       -0.65756106, -0.36641183,  0.32435626,  0.21444224, -0.5458109 ,
        0.24145347, -0.28886443, -0.02647865, -0.3128136 , -0.3395641 ,
       -0.39964452, -0.15359847, -0.28862628, -0.5121813 ,  0.27

In [49]:
# Get the indices of all words in the vocabulary
word_indices = model2.wv.key_to_index.values()

# Retrieve word vectors for all words in the vocabulary
word_vectors = [model2.wv.get_vector(model2.wv.index_to_key[i]) for i in word_indices]

# Convert to a numpy array
X = np.array(word_vectors)

In [50]:
X

array([[-4.5927683e-01, -2.2800609e-01,  2.9568579e+00, ...,
         7.8830995e-02, -1.3313805e+00,  2.3925836e-01],
       [ 3.0214467e+00, -2.5529188e-01,  6.5442693e-01, ...,
        -9.0269220e-01,  1.6584750e+00, -2.4772501e+00],
       [ 1.6141729e+00,  1.2559657e+00, -7.0097297e-02, ...,
        -1.3677220e+00,  6.9870234e-01, -1.7924949e+00],
       ...,
       [ 5.1042805e-03, -1.0343750e-02,  3.5496547e-03, ...,
        -1.1301988e-02, -2.1814755e-03, -1.4661608e-04],
       [ 1.4912755e-03,  3.4428949e-03,  8.2980783e-05, ...,
         1.3335879e-02, -2.5205825e-02,  5.9872014e-03],
       [ 7.2954148e-03,  2.1466103e-04, -2.5553224e-03, ...,
         4.7691762e-03,  8.7930178e-03, -1.4611298e-02]], dtype=float32)

In [51]:
from sklearn.decomposition import PCA

In [52]:
pca = PCA(n_components=2)

In [53]:
result = pca.fit_transform(X)

In [54]:
result

array([[ 4.670201  ,  1.2844198 ],
       [ 8.227142  , 13.055797  ],
       [ 7.6027403 , 11.022284  ],
       ...,
       [-0.20182538,  0.01627246],
       [-0.33327317,  0.08406781],
       [-0.21554455,  0.08925216]], dtype=float32)

In [55]:
import io

In [57]:
out_v = io.open('/content/drive/MyDrive/DataScience/Auditoriski/vecs.tsv', 'w', encoding='utf-8')

In [58]:
out_m = io.open('/content/drive/MyDrive/DataScience/Auditoriski/meta.tsv', 'w', encoding='utf-8')

In [63]:
words = model2.wv.index_to_key
words

['RT',
 'the',
 'to',
 'Bitcoin',
 'and',
 'of',
 'a',
 'is',
 'in',
 '',
 'for',
 '#Bitcoin',
 '#bitcoin',
 'on',
 'you',
 'our',
 'with',
 '@bethereumteam:',
 'The',
 '-',
 '#cryptocurrency',
 'your',
 '#blockchain',
 'that',
 'will',
 'are',
 'be',
 'bitcoin',
 '&amp;',
 'have',
 '#crypto',
 'I',
 'out',
 'at',
 '#ethereum',
 'about',
 'by',
 'Airdrop',
 'can',
 'We',
 'this',
 'more',
 'from',
 '#Blockchain',
 'how',
 'what',
 "we're",
 'been',
 'we',
 'it',
 'get',
 '#Satoshi',
 '@GymRewards:',
 'as',
 'A',
 'has',
 'Do',
 'my',
 '#Airdrop',
 '#Airdrop\nNew',
 'Bitcoin!',
 'first',
 'much',
 'successful',
 'still',
 'Blockchain',
 'all',
 'make',
 'In',
 'an',
 'Checkout',
 '#Earn_Money',
 '1',
 '#Cybersecurity',
 'How',
 '#bitcointalk',
 'Will',
 '#btc',
 'not',
 'do',
 'up',
 '#ICO',
 'just',
 'find',
 'automatically',
 'hour',
 'via',
 'traders',
 '#tokenssale',
 '#ANN',
 'To',
 'Copy',
 '#Gymrewards',
 'https://t.co/J5xnJJr7Sa',
 'https://t.co/Bm9sIxiiwU',
 'or',
 'why',
 'art

In [67]:
word = model2.wv.index_to_key[2]
word

'to'

In [68]:
model2.wv[[model2.wv.index_to_key[2]]]

array([[ 1.6141729e+00,  1.2559657e+00, -7.0097297e-02,  2.3423122e-01,
        -9.8403925e-01, -1.3035219e+00, -1.7612958e+00,  1.2258183e+00,
         1.8024780e+00,  2.7973890e-01,  1.7147141e+00,  3.5152441e-01,
        -1.4863145e-01,  3.8409629e-01,  1.5955898e-01, -4.9360716e-01,
         3.5069174e-01, -2.9934640e+00, -7.7466947e-01, -3.3597216e-01,
        -1.2416195e+00, -1.8440671e-01,  3.4846032e+00,  1.4938569e+00,
        -2.5297892e+00, -7.0754863e-02, -3.5090990e-02,  6.4863521e-01,
         2.0195279e+00, -2.9348350e+00, -1.1484610e+00, -7.7138871e-01,
        -1.9859470e-01,  2.1654589e-01, -1.2684824e+00,  7.8499783e-04,
         7.3122817e-01, -1.4100187e+00, -8.3529174e-01,  6.2429285e-01,
         3.0627761e+00,  1.1162409e+00, -1.2704436e+00, -1.9433410e+00,
        -6.9509637e-01,  2.7845329e-01,  1.5062704e+00, -4.6594670e-01,
         1.1249908e+00, -5.9265894e-01,  4.3927733e-02, -3.7994936e-01,
        -4.8848313e-01, -3.6489778e+00, -2.7314794e+00, -6.51768

In [69]:
for index in range(0,len(model2.wv.index_to_key)):
  word = model2.wv.index_to_key[index]
  vec = model2.wv[word]
  out_m.write(word+"\n")
  out_v.write("\t".join([str(x) for x in vec]) + "\n")

In [70]:
out_v.close()

In [71]:
out_m.close()

# Named Entity Recognition


In [72]:
import spacy

In [73]:
import en_core_web_sm

In [75]:
nlp = en_core_web_sm.load()
# loadiranje na celiot model za angliski jazik

In [76]:
doc = nlp(df['text'][0])

In [77]:
doc

@lopp @_Kevin_Pham @psycho_sage @naval But @ProfFaustus (dum b a ss) said you know nothing about #Bitcoin ... 😂😂😂 https://t.co/SBAMFQ2Yiy

In [79]:
doc.ents

(@lopp @_Kevin_Pham @psycho_sage, about #Bitcoin)

In [85]:
doc.ents[0].label_

'PERSON'

In [78]:
print([(X.text,X.label_) for X in doc.ents])

[('@lopp @_Kevin_Pham @psycho_sage', 'PERSON'), ('about #Bitcoin', 'MONEY')]


In [86]:
from spacy import displacy

In [87]:
displacy.render(nlp(df['text'][50]),jupyter=True,style='ent')

In [88]:
displacy.render(nlp(df['text'][50]),jupyter=True,style='dep')